# Generated by Django 4.0.5 on 2022-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('type', models.CharField(choices=[('Back-end', 'Back End'), ('Front-end', 'Front End'), ('iOS', 'Ios'), ('Android', 'Android')], max_length=25)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
