# Generated by Django 4.0.5 on 2022-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_alter_issue_assigned_to_alter_issue_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
