# Generated by Django 4.0.5 on 2022-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Faible', 'Low'), ('Moyenne', 'Medium'), ('Élevée', 'High')], default='Moyenne', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('À faire', 'To Do'), ('En cours', 'In Progress'), ('Terminé', 'Done')], default='À faire', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Tâche', 'Task'), ('Amélioration', 'Upgrade')], default='Tâche', max_length=50),
        ),
    ]
