# Generated by Django 4.0.5 on 2022-07-12 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0007_alter_issue_priority_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='project_management.issue'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Créateur', 'Creator'), ('Contributeur', 'Contributor')], default='Contributeur', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='issue_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
