# Generated by Django 4.0.5 on 2022-07-13 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0009_remove_issue_assigned_to_issue_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='issue_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
